# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: def6d5d
_src_path: gh:makukha/copython
author_email: m.makukha@gmail.com
author_name: Michael Makukha
copyright_year: 2025
docs: github_readme
docs_url: https://github.com/makukha/scrap#readme
github_slug: makukha/scrap
github_url: https://github.com/makukha/scrap
module_name: scrap
openssf_bp_id: '10675'
project_name: scrap
project_version: 0.0.0
pypi_package_name: scrap
pypi_url: https://pypi.org/project/scrap
python_version: 3.13.3
python_version_minor: '3.13'
