[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scrap"
version = "0.0.0"
description = "Web testing utilities"
readme = "README.md"
requires-python = ">=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4"
dependencies = []
