version: '3'

tasks:

  init:
    desc: Initialize dev environment.
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    cmds:
      - brew install
          poetry
          pyenv
      - pyenv install --skip-existing $(pyenv local)

  install:
    desc: Install app in dev environment.
    cmds:
      - poetry lock --no-update
      - poetry install

  build:
    desc: Build Docker image.
    cmds:
      - poetry lock --no-update
      - poetry build --no-interaction
